### PR TITLE
Make usage of the Jenkins Credential Plugin instead of username/password and manage configuration by id instead of name

### PR DESCRIPTION
**Pull request by ghost**
Instead if using separate username and password for each share, it would be nice/better to store the credentials (username/password) centralized in Jenkins, making updates of username/password for a share much easier, especially when some organization needs to update their password against a share for each third months.

Second, instead of using the name as the primary key, its better to use a id, making it possible for end users to change a shares name, without having to update the jobs to point to the 'new' name of a share.

Feedback wanted :)

Best regards
/Jonas M

### CODE REVIEW

**Comment by slide** [comment]
This could be done with a @DataBoundSetter now, are you still interested in getting this merged?

**Comment by jonasmkarlsson** [comment]
I have removed my fork of this repository. I still think it is a good idea to make use of the credential Id from Jenkins, this to avoid changing username for each CIFS share. If you can make the necessary changes and use this @databoundsetter, it would be great, but I don't have the time right now.

**Comment by ChristianCiach** [comment]
> I am implementing support for the credentials plugin

Is there progress on this?

**Comment by slide** [comment]
There is, but slow. Since almost all publish-over plugins are based in this one, I have to update all of them and test all of them.

**Pull request closed without merging**
